#!/usr/bin/env python
"""Self-contained reproduction script — generated by vivarium-dashboard.

Run from anywhere with the workspace's virtualenv, e.g.:
    .venv/bin/python quantum-multi-omic-classifier.py

Figures are written to:  reports/notebooks/figures
Set RERUN = False (below) to render the committed runs.db without re-simulating.
"""
import os as _os
import sys as _sys

# YAML / study text is UTF-8; force UTF-8 mode so file reads don't depend on the
# shell locale (a bare-CLI run under an ASCII locale otherwise crashes on non-ASCII).
if _os.environ.get("PYTHONUTF8") != "1":
    _os.environ["PYTHONUTF8"] = "1"
    _os.execv(_sys.executable, [_sys.executable, *_sys.argv])


# # Quantum Multi-Omic Classifier — Genotype-to-Phenotype Mapping via Data Re-Uploading
#
# _Investigation `quantum-multi-omic-classifier` — coder reproduction notebook._
#
# **Question.** Can a multi-qubit, cross-modality entangled quantum classifier outperform classical ML baselines in predicting binary phenotypes from synthetic multi-omic data?
#
# An investigation into whether a purpose-built multi-qubit quantum classifier can improve phenotype prediction from multi-omic data by using entanglement to model biological cross-talk between molecular layers.
#
# ---
#
# This notebook re-runs each study with the workspace's own process-bigraph protocol and renders its figures. The text states the **question and parameters** only — the figures produced by each run are the results. Set `RERUN = False` in the setup cell to render the committed `runs.db` without re-simulating.

"""Self-contained reproduction of this investigation.

Generated by vivarium-dashboard (notebook_export). Each study below is re-run
live with the workspace's own process-bigraph protocol and its figures are
rendered from the resulting runs.db.
"""
import os
import sys
from pathlib import Path

# Resolve the repository root robustly so this notebook runs from a fresh clone
# at ANY path with no setup (no env var, no path editing). Priority:
#   1. $VIVARIUM_REPO, if it points at a real directory;
#   2. walk up from the notebook's working directory for the repo markers
#      (a directory holding both 'workspace/' and 'pyproject.toml') — Jupyter
#      starts in the notebook's dir, so a committed notebook finds its own root;
#   3. the absolute path it was generated for (back-compat for old layouts);
#   4. the current working directory (last resort).
def _find_repo_root(_start):
    for _cand in (_start, *_start.parents):
        if (_cand / "workspace").is_dir() and (_cand / "pyproject.toml").is_file():
            return _cand
    return None

REPO = None
_env = os.environ.get("VIVARIUM_REPO")
if _env and Path(_env).is_dir():
    REPO = Path(_env)
if REPO is None:
    REPO = _find_repo_root(Path.cwd().resolve())
if REPO is None and Path('/home/runner/work/viva-pennylane-data-reuploading/viva-pennylane-data-reuploading').is_dir():
    REPO = Path('/home/runner/work/viva-pennylane-data-reuploading/viva-pennylane-data-reuploading')
if REPO is None:
    REPO = Path.cwd()
sys.path.insert(0, str(REPO))
# Composite specs use repo-root-relative paths (datasets, caches), and the
# workspace's runner/renderer assume cwd == repo root — so run from there.
os.chdir(REPO)

# Re-simulate from scratch? Set False to render the committed runs.db (fast).
RERUN = True

# --- standard process-bigraph protocol: register the workspace's Core ---
from pbg_pennylane_data_reuploading.core import build_core
core = build_core()

# --- imported from the repo this notebook was generated for ---


import contextlib as _contextlib, io as _io
@_contextlib.contextmanager
def quiet():
    """Silence the simulator's verbose per-step stdout so the notebook
    output stays readable (the figures below are the results)."""
    with _contextlib.redirect_stdout(_io.StringIO()):
        yield

import html as _htmlmod
def show_viz(_h, height=560):
    """Display a visualization's HTML in an isolated iframe.

    The figures embed their own scripts (e.g. Plotly); JupyterLab does not
    execute <script> tags from display(HTML(...)), so an iframe srcdoc is
    used instead — the browser runs the scripts inside the frame."""
    display(HTML(
        '<iframe srcdoc="{}" style="width:100%;height:{}px;border:0">'
        '</iframe>'.format(_htmlmod.escape(_h, quote=True), height)
    ))

import json as _json
def describe_spec(spec):
    """Print a composite spec's structure (parameters, processes, wiring)
    then the full editable dict. The spec is plain data — assign to any
    field (e.g. spec['state'][proc]['config'][...]) before building."""
    print("composite:", spec.get("name"))
    if spec.get("description"):
        print("description:", str(spec["description"]).strip())
    _params = spec.get("parameters") or {}
    if _params:
        print("\nparameters (filled into ${name} placeholders):")
        for _p, _pdef in _params.items():
            print(f"  {_p}: default={_pdef.get('default')!r}  type={_pdef.get('type')}")
    print("\nprocesses (node -> address):")
    for _node, _body in (spec.get("state") or {}).items():
        if not (isinstance(_body, dict) and _body.get("_type") == "process"):
            continue
        print(f"  {_node}  ->  {_body.get('address')}   interval={_body.get('interval')!r}")
        for _port in ("inputs", "outputs"):
            if _body.get(_port):
                print(f"      {_port} ports: {_body[_port]}")
    print("\nfull editable spec dict:")
    print(_json.dumps(spec, indent=2, default=str))

# ## Study: `genotype-phenotype-baseline`
#
# **Question.** What is the best AUC-ROC and F1 score achievable with classical ML methods on synthetic multi-omic phenotype prediction, to establish a baseline for quantum classifier comparison?
#
# **Objective.** Train Random Forest and Logistic Regression on synthetic multi-omic data
# and report accuracy, AUC-ROC, F1, precision, and recall.
#
# **Hypothesis.** Random Forest will outperform Logistic Regression by capturing nonlinear cross-modality interactions, but both will serve as strong baselines.

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: genotype-phenotype-baseline ===
STUDY = 'genotype-phenotype-baseline'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `quantum-classifier-evaluation`
#
# **Question.** Can the GenotypeToPhenotypeProcess match or exceed classical ML baselines in predicting binary phenotypes from synthetic multi-omic data?
#
# **Objective.** Train the GenotypeToPhenotypeProcess with M=4 modalities, F=6 features per
# modality on synthetic data, and compare accuracy, AUC-ROC, F1, precision,
# and recall against RF and LR baselines.
#
# **Hypothesis.** The quantum classifier will achieve competitive AUC-ROC (>= 0.80) on synthetic data with strong cross-modality interactions, benefiting from the CNOT entanglement chain.

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: quantum-classifier-evaluation ===
STUDY = 'quantum-classifier-evaluation'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `v2ecoli-real-data`
#
# **Question.** Can the ZarrMultiOmicLoader correctly extract features from real v2ecoli zarr stores, and can the GenotypeToPhenotypeProcess classify phenotypes from this biologically realistic data?
#
# **Objective.** Run a v2ecoli simulation with XArrayEmitter, load the zarr output with
# ZarrMultiOmicLoader, map observables to modality slots, and train the
# quantum classifier on real simulated multi-omic data.
#
# **Hypothesis.** The ZarrMultiOmicLoader will correctly handle real v2ecoli zarr structure. The quantum classifier will achieve non-trivial accuracy (>0.65 AUC-ROC).

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: v2ecoli-real-data ===
STUDY = 'v2ecoli-real-data'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Open decisions
# - Which classical baselines to include (RF, LR, XGBoost, SVM)?
# - What is the minimum acceptable AUC-ROC for claiming quantum advantage?
# - Should evaluation use cross-validation or fixed train/test split?
